### ISSUE TITLE
실무에 바로 적용할 수 있는 안드로이드 8.0 앱 프로그래밍 ....

### ISSUE THREAD

**Issue by parkskwan** [Fluxus-M/Android-Tutorials#1]
안녕하세요, 

출판사에 문의를 했더니 이곳에 질문을 하면 작가분들이 답변을 해 줄 것이라고 해서요.

안드로이드 8.0 앱 프로그래밍 책을 구매해서 읽고 있는 독자 입니다.

제가 목차를 제대로 확인 하지 않아서 

마이크를 이용한 녹음을 전화통화 녹음으로 착각 했습니다.

혹시 실례가 되지 않는 다면 작가분들께 

전화통화 녹음에 대한 프로그램 또는 참고 할 만한 사이트를 요청 할 수 있나 해서

문의를 드립니다. 

감사합니다.

**Comment by parkhunwoo** [comment]
@parkskwan

안녕하세요.
답변이 늦었습니다.

통화녹음의 경우에는 구글에서 정책을 변경하여
안드로이드 9.0(파이) 부터는 통화녹음 API를 막아 놓았습니다.

이전 버전의 안드로이드에서도 사용하기가 쉽지 않습니다

시스템의 루트 권한을 자유롭게 가지는 제조사 레벨이 아니라면
개인 개발자는 앞으로 통화녹음기능 앱을 만들기는 어려울 것 같습니다.

감사합니다.

<참고>
논란의 통화녹음... 최신 안드로이드에선 어떻게 바뀌나? [IT동아 / 2018.8.27]
http://it.donga.com/28092/ 

cc.  @GMLim @parkhunwoo
